server {
    # SSL/TLS Configuration
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    root /var/www/wordpress;
    index index.php index.html;
    server_name ybassour.42.fr;

    # Adminer (PHP-FPM)
    location ~ ^/adminer(/.*|$) {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        fastcgi_pass adminer:9000;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param HTTP_REFERER $http_referer;
        fastcgi_index index.php;
    }

    # Force trailing slash
    location = /cadvisor {
        return 301 https://$host/cadvisor/;
    }

    # Reverse proxy
    location ^~ /cadvisor/ {
        proxy_pass http://cadvisor:8080/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect / /cadvisor/;
    }
    location ^~ /static_site/ {
        proxy_pass http://static_site:80/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect / /static_site/;
    }
    # WordPress
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

