server {
    # SSL/TLS Configuration
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Root and Index
    root /var/www/wordpress;
    index index.php index.html;
    server_name ybassour.42.fr;

    location ~ ^/adminer(/.*|$) {
        include fastcgi_params;
        
        # This MUST match the path you just verified with 'head'
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        
        # Pass to your adminer container
        fastcgi_pass adminer:9000;
        fastcgi_param REQUEST_URI $request_uri;
        # Important: Adminer needs this to handle its internal links
        fastcgi_param HTTP_REFERER $http_referer;
          # 5. Fix for potential redirection loops
        fastcgi_index index.php;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Pass PHP scripts to FastCGI server (WordPress container)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
