version: '3.8'

services:


  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception
    volumes:
      - db-data:/var/lib/mysql
    restart: always



  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:inception
    networks:
      - inception
    volumes:
      - redis-data:/data # Better for Redis persistence (RDB/AOF files)
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]


  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    volumes:
      - wp-data:/var/www/wordpress
    restart: always


  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:inception
    # ADD THIS LINE TO LOAD YOUR .ENV FILE
    env_file: .env
    ports:
      - "21:21"
      - "30000-30050:30000-30050"
    volumes:
      - wp-data:/var/www/html
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PWD=${FTP_PWD}
    networks:
      - inception
    restart: always


  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wp-data:/var/www/wordpress
    restart: always

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/credentials.txt
  wp_user_password: # Add this line
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/redis

