# Run in the foreground for Docker; use YES if running as a system service
background=NO
pam_service_name=vsftpd

# Network Settings
listen=YES
listen_ipv6=NO
listen_address=0.0.0.0
listen_port=21

# Access & Permissions
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Security & Chroot (Required for modern vsftpd)
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO

# Directory settings
local_root=/var/www/html

# Passive Mode (FIXED for Localhost)
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30050
# Since you are on your PC, use 127.0.0.1 for local testing
pasv_address=127.0.0.1



secure_chroot_dir=/var/run/vsftpd/empty

