# Run in the foreground for Docker; use YES if running as a system service
background=NO
pam_service_name=vsftpd

# Example vsftpd.conf settings for Inception
# Directory settings
local_root=/var/www/wordpress
anon_root=/var/www/wordpress
user_sub_token=$USER

# Network Settings
listen=YES
listen_ipv6=NO
listen_address=0.0.0.0
listen_port=21

# Access & Permissions
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Security & Chroot (Required for modern vsftpd)
chroot_local_user=YES
allow_writeable_chroot=YES
seccomp_sandbox=NO


# Passive Mode (FIXED for Localhost)
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30050
# Since you are on your PC, use 127.0.0.1 for local testing
# pasv_address=127.0.0.1

# # Change or remove these lines:
# pasv_enable=YES
# pasv_min_port=30000
# pasv_max_port=30050
# REMOVE THIS LINE: pasv_address=127.0.0.1
# ADD THIS LINE:
pasv_promiscuous=YES

secure_chroot_dir=/var/run/vsftpd/empty

